version: '3.1'
services:
  pulsar:
    image: apachepulsar/pulsar:2.10.2
    container_name: pulsar
    ports:
      - '8080'
      - '6650'
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
    command: /bin/bash -c "bin/pulsar standalone"
volumes:
  pulsardata:
  pulsarconf:
